% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={p8130\_hw2\_yl5508},
  pdfauthor={Yifei LIU (yl5508)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{p8130\_hw2\_yl5508}
\author{Yifei LIU (yl5508)}
\date{2023/10/11}

\begin{document}
\maketitle

\hypertarget{problem-1}{%
\subsection{Problem 1}\label{problem-1}}

\textbf{(a)}
\(P(exactly\ 40)=\binom{56}{40} \cdot (0.73)^{40} \cdot (1 - 0.73)^{16}=0.113=11.3\%\)

\textbf{(b)}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{trial }\OtherTok{=} \DecValTok{56}
\NormalTok{success }\OtherTok{=} \DecValTok{39}
\NormalTok{p }\OtherTok{=} \FloatTok{0.73}
\FunctionTok{print}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pbinom}\NormalTok{(success,trial,p))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6678734
\end{verbatim}

The probability that at least 40 of them have at least 1 checkup is
0.6678734.

\textbf{(c)} The condition we should check before using Poisson
appoximation to binomial is:\\
- n must be large (n\textgreater100): in this problem,
n=56\textless100.\\
- Probability of success p should be small (p\textless0.01): in this
problem, p is 0.73.\\
As a result, we should not use Poisson as an approximation to
binomial.\\
\textbf{(d)} Expectation of a binomial R.V. is \texttt{E{[}X{]}\ =\ np},
which is 40.88.\\
\textbf{(e)} Variance of a binomial R.V. is \texttt{Var(x)\ =\ np(1-p)},
which is 11.0376. The standard deviation of it would be
3.3222884(\(sd=\sqrt{Var(x)}\)).

\hypertarget{problem-2}{%
\subsection{Problem 2}\label{problem-2}}

\textbf{(a)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{ppois}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0619688
\end{verbatim}

The PMF of Poisson distribution can be expressed as
\(P(X = k) = \frac{e^{-\lambda} \cdot \lambda^k}{k!}\).\\
For tornado happened fewer than 3 times,
\(P(X < 3) = P(X = 0) + P(X = 1) + P(X = 2) = \sum_{k=0}^{2}\frac{e^{-6} \cdot 6^k}{k!} = 0.062 = 6.2\%\).

\textbf{(b)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{dpois}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.08923508
\end{verbatim}

The probability that tornado will happen exactly 3 tims is 0.0892351.

\textbf{(c)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{ppois}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{6}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8487961
\end{verbatim}

The probability that tornado will happen more than 3 tims is 0.8487961.

\hypertarget{problem-3}{%
\subsection{Problem 3}\label{problem-3}}

\textbf{(a)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\FunctionTok{pnorm}\NormalTok{(}\DecValTok{137}\NormalTok{,}\DecValTok{128}\NormalTok{,}\FloatTok{10.2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.188793
\end{verbatim}

The probability of a selected American man (20-29) with systolic blood
pressure above 137.0 is 0.188793.

\textbf{(b)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{pnorm}\NormalTok{(}\DecValTok{125}\NormalTok{,}\DecValTok{128}\NormalTok{,}\FloatTok{10.2}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{50}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01877534
\end{verbatim}

The population distribution of the R.V. is normal and the sample size is
larger than 30. So, we can denote the sampling distribution as
\(\overline{X}\sim N(\mu,\frac{\sigma^{2}}{n})\), which is
\(\overline{X}\sim N(128,\frac{10.2}{\sqrt{50}})\) in this problem. The
probability that sample mean will be less than 125.0 is 0.0187753.

\textbf{(c)}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{qnorm}\NormalTok{(}\FloatTok{0.9}\NormalTok{,}\DecValTok{128}\NormalTok{,}\FloatTok{10.2}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{40}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 130.0668
\end{verbatim}

For sample size of 40, the sampling distribution would follow:
\(\overline{X}\sim N(128,\frac{10.2}{\sqrt{40}})\). The 90th percentile
of the sampling distribution is 130.0668372.

\hypertarget{problem-4}{%
\subsection{Problem 4}\label{problem-4}}

\textbf{(a)}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#t statistic}
\NormalTok{t\_975 }\OtherTok{=} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{,}\DecValTok{39}\NormalTok{)}
\FunctionTok{print}\NormalTok{(t\_975)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.022691
\end{verbatim}

For true σ from population is unknown, we need to calculate the
estimated standard error:
\(\frac{s}{\sqrt{n}}=\frac{10}{\sqrt{40}}=1.58\).\\
So, the confidence interval(CI) for the population mean pulse rate would
be shown as
\(P(\overline{X}-2.02\sigma_{\overline{X}}<\mu<\overline{X}+2.02\sigma_{\overline{X}}) = 0.95\),
among which CI is \textbf{\(76.81<\mu<83.19\)}.

\textbf{(b)} The confidence interval calculated above means that, for
most (95\%) of the random variables, \(\overline{X}\) will fall within
+/- 2.02 estimated SE of the true mean \(\mu\). The 95\% CI is
\((76.81,83.19)\).

\textbf{(c)}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#statistic t}
\NormalTok{t }\OtherTok{=} \FunctionTok{abs}\NormalTok{((}\DecValTok{80{-}70}\NormalTok{)}\SpecialCharTok{/}\NormalTok{(}\DecValTok{10}\SpecialCharTok{/}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{40}\NormalTok{)))}
\NormalTok{t\_995 }\OtherTok{=} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.995}\NormalTok{,}\DecValTok{39}\NormalTok{)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{c}\NormalTok{(t,t\_995))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 6.324555 2.707913
\end{verbatim}

Using method of tests for the mean of a normal distribution with known
variance.\\
Suppose that \(\mu_0=70\), and \(H_0:\mu=\mu_0\) vs
\(H_1:\mu\neq\mu_0\).\\
With the significant level \(\alpha=0.01\), test statistic is
\(t=\frac{\overline{X}-\mu_0}{s/\sqrt{n}}=\frac{80-70}{10/\sqrt{40}}=6.32\).\\
Criteria:\\
- Reject \(H_0\): if \(|t|>t_{39,0.995}\),\\
- Fail to reject \(H_0\): if \(|t|\leq t_{39,0.995}\).
\(t_{39,0.995}=2.71\).\\
Cause \(|t|>t_{39,0.995}\), we can reject \(H_0\).\\
Result: with significant level \(\alpha=0.01\), we should reject \(H_0\)
and the mean pulse of young women suffering from fibromyalagia isnot
equal to 70. In other words, the possibility of getting a sample with a
mean equivalent to 80 or more extreme than that is less than 1\%, given
that the population mean is 70.

\end{document}
